### ISSUE TITLE
Does it works with Fiori Elements

### ISSUE THREAD

**Issue by jberthe** [ui5-community/ui5-journey-recorder#33]
Hello,

I have tried to load the extension over Fiori Eléments application, I see the red boxes but the extension seams not be linked to the application.
![image](https://user-images.githubusercontent.com/6067155/203742130-7bc26e25-b917-4b8a-818c-a28e3c5ee2e2.png)
Regards,

**Comment by tabris87** [comment]
Hi, 

it looks like you lost the connection between the Journey Recorder and your application.
While on the main-page it won't be possible to record anything.

I try to get my hands on a Fiori Elements Application to reproduce this.

**Comment by tabris87** [comment]
Hi, 

so i tried it with the [Fiori-Elements Application from the UI5-Demo-Apps](https://ui5.sap.com/test-resources/sap/suite/ui/generic/template/demokit/sample.manage.products.sepmra/test/index.html?sap-ui-theme=sap_horizon_dark#masterDetail-display).

So the Journey Recorder was able to connect to the page and record.
[Here is the Recording: Fiori_Elements.txt](https://github.com/ui5-community/ui5-journey-recorder/files/10290132/Fiori_Elements.txt). 
Please rename the file to "Fiori_Elements.json", because Github accepts no JSON-Files.
