### ISSUE TITLE
SAPUI5 Freestyle app vs Fiori elements app recording

### ISSUE THREAD

**Issue by jtvvalliparampil** [ui5-community/ui5-journey-recorder#47]
hello , 

After generating wdi5 code using UI5 Journey Recorder, we noticed the code generated for a very small SAPUI5 Freestyle app was missing details for the navigation path and had small mistakes related to syntax. 

![image](https://user-images.githubusercontent.com/121968985/236046928-da784d97-8045-4908-8d9c-f8c1146542c7.png)

The code generated for Fiori elements worked as expected.  Is the UI5 Journey Recorder intended to work only with Fiori elements? 

The dependencies are:

"@babel/eslint-parser": "7.14.7",
"@sap-ux/ui5-middleware-fe-mockserver": "2",
"@sap/eslint-plugin-ui5-jsdocs": "2.0.5",
"@sap/ui5-builder-webide-extension": "^1.1.8",
"@sap/ux-ui5-tooling": "1",
"@sapui5/ts-types": "~1.108.0",
"@ui5/cli": "^3.0.0",
"@wdio/cli": "^7.31.1",
"@wdio/local-runner": "^7.31.1",
"@wdio/mocha-framework": "^7.30.2",
"@wdio/spec-reporter": "^7.31.1",
"chromedriver": "^112.0.1",
"eslint": "7.32.0",
"eslint-plugin-fiori-custom": "2.2.1",
"mbt": "^1.2.18",
"ui5-task-zipper": "^0.5.0",
"wdio-chromedriver-service": "^7.3.2",
"wdio-ui5-service": "^1.3.3"

UI5 Journey Recorder 0.2.1

Thank You,
Joe Valliparampil.

**Comment by tabris87** [comment]
Hi, 

thanks for the small syntax issues, i will adress them as soon as possible.

For the wrong path: What's the correct one? 
Or better can you send an export of the Step/Journey? Another possible way is the url for the page, because we determine the path from this url.

As for your question: No the UI5-Journey-Recorder is not only for Fiori-Elements it should work for all types of UI5-Applications. Sometimes it's hard to determine some correct code-generations. As well as the test-setups differ. 
Maybe you can describe which code-fragments fit not for your tests?

Best regards
Adrian Marten
